### ISSUE TITLE
Sometimes the UI takes forever to launch

### ISSUE THREAD

**Issue by mbmbmbmb** [NHLGames/NHLGames#10]
[reddit complaints](https://www.reddit.com/r/NHLStreams/comments/49bf9n/tool_nhlgames_stream_nhl_games_in_hd_and_60fps/d1ohp28)

I believe this has to do with the `LocateEXE` method in `FileAccess.vb`. Specifically, I think it gets super slow and shitty when it can't find what it's looking for and falls back to recursively searching everything in Program Files.

The program does 2 time consuming things before shows the UI:

1) Goes to the remote server to see if the version is up to date (Should be pretty quick, but if their internet is down or something, could be done async)

2) Locates the EXE for MPC 64 bit (Then MPC 32 bit if it doesn't find 64), and VLC, and livestreamer. If it doesn't find an exe where it expects it to, or it isn't installed (for example, someone might only have MPC 32-bit installed. They don't need MPC 64, VLC, and MPC 32 installed) it seems to get extremely overzealous with where it searches and recursively searches Program Files, [I believe when it reaches this point](https://github.com/NHLGames/NHLGames/blob/master/WindowsApplication1/Utilities/FileAccess.vb#L56). 

Easiest way to reproduce this is to delete your NHLGames.exe.config and delete the 'livestreamer-v1.12.2' folder from your output directory. Then it will go on the hunt, even with an SSD and not a ton installed in Program Files it takes over 5 seconds.

Seems super overkill. If someone installs it in a non-default location, make them go search for it.

**Comment by NHLGames** [comment]
You're totally right.  Since there's the ability to set custom paths now, this is unnecessary.

**Comment by NHLGames** [comment]
Fixed in latest release.
