### ISSUE TITLE
reloading games causing issues

### ISSUE THREAD

**Issue by jwallet** [NHLGames/NHLGames#116]
clicking more than one times on reload will cause the request to fail because it now looking for new streams, so sending requests, and those need to be asynchronous otherwise it will fail if user restarts it before it's done.

- convert threads into tasks
- wait for tasks to end
- make web request async and await the webresponse as task of string

**Comment by d-kar** [comment]
Sometimes if you click multiple times you get duplicate games like this:
![image](https://user-images.githubusercontent.com/10633128/32424191-d4f42100-c278-11e7-964d-e1ac372a9ae0.png)

**Comment by jwallet** [comment]
i let the refresh button available cause if the app fails getting streams, the user can retry by clicking on refresh, i did not think some one will actually double click refresh just to break it. but i guess it might be better to disabled the nav bar until games are loaded. if the app fails to get games, the user will have to restart

**Comment by jwallet** [comment]
yes i disabled it
