### ISSUE TITLE
Dark Theme?

### ISSUE THREAD

**Issue by goldenpipes** [NHLGames/NHLGames#118]
is this on the to do list? :)

**Comment by jwallet** [comment]
i will consider it

**Comment by jwallet** [comment]
i think i'm gonna close it since we have many other things to work on and this will take too much effort for almost no value.

**Comment by jwallet** [comment]
Work in progress
![image](https://user-images.githubusercontent.com/23088305/38847904-f4395958-41d1-11e8-875f-fa1edc0c0ce6.png)
