### ISSUE TITLE
vod url not working anymore 

### ISSUE THREAD

**Issue by jwallet** [NHLGames/NHLGames#127]
https://www.reddit.com/r/nhl_games/comments/7e4wus/v110_released_big_update/dq48abu/

**Comment by jwallet** [comment]
got it fixed, every links work now

**Comment by NHLGames** [comment]
Do you think we should release a minor revision to fix this issue?

**Comment by jwallet** [comment]
We can release a patch version 1.1.0.1 . You will have to write in the changelog msgbox something like 1.1.0 patch1 because i still check for build version/patch but i do not show build version on the ui and message box. But in the assembly its always 4 digits long. 1.1.0.0 .. on github we can tag it as 1.1.0.1 or 1.1.0.patch1.. i will push something soon

**Comment by jwallet** [comment]
However On the server where i get version.txt it should be 1.1.0.1
