### ISSUE TITLE
No games available - 403 forbidden

### ISSUE THREAD

**Issue by jevy** [NHLGames/NHLGames#128]
Turned it on tonight and the console said for every game it was 403 forbidden. Worked fine on Monday.

**Comment by jwallet** [comment]
are you running 1.1.0

**Comment by jwainz** [comment]
I am having a similar issue. Every line on the console panel reads "[19:18:14] Warning: Game stream CGY vs CBJ on FSOH not found on the server: The remote server returned an error: (403) Forbidden."    I can stream games from previous days but no live streams

**Comment by jevy** [comment]
Yes.

**Comment by ppmil** [comment]
same over here 403 no streams on any games

**Comment by chefsuperstar** [comment]
same as everyone else....403 forbidden and I tried both fixes that were recommended and still no streams available.

**Comment by jwallet** [comment]
our nhl account got banned, sorry no games for sometimes
