### ISSUE TITLE
Feature idea - Announcements

### ISSUE THREAD

**Issue by NHLGames** [NHLGames/NHLGames#129]
I was thinking if the server is ever not working (like yesterday), we should be able to push announcements to let users know what's going on.  This could work similarly to the version check / changelog feature

**Comment by jwallet** [comment]
Great idea. And the thing im working on will stop the app from trying to get links that are broken or the app has any issue

**Comment by jwallet** [comment]
https://showtimes.ninja/static/announcement.txt
