### ISSUE TITLE
Spotify integration does not work if Spotify was installed via Microsoft Store

### ISSUE THREAD

**Issue by jlj-ee** [NHLGames/NHLGames#131]
If the Windows 10-specific Spotify app is installed (from the Microsoft store, instead of the win32 spotify.com desktop download), the ad detection module will not be able to detect that Spotify is installed (or launch it).
This is because the executable now resides at AppData\Local\Microsoft\WindowsApps\Spotify.exe, which does not seem to be part of the search path in the Spotify module. The result is that NHLGames will return **Warning: Ad Detection: Spotify is not installed** even if the Spotify app is installed.

**Comment by jwallet** [comment]
Thanks for the feedback . We will add it at some point

**Comment by jwallet** [comment]
it's fixed, coming in the next version
