### ISSUE TITLE
No stream available

### ISSUE THREAD

**Issue by tlfs2222** [NHLGames/NHLGames#133]
Just downloaded v1.10 and get the, "No stream available" message for every game. I did the Command Prompt thing to get the IP address and the host file has that entry in it.  The Hosts file check says the IP addresses match.  Haven't tried the Run as Administrator fix yet because it looks like more than I want to get involved with and it looks like everything is correct.  Any suggestions?

GREAT app. Been using it since version b. If I get it working again I will definitely contribute.

Thanks!

**Comment by jwallet** [comment]
our NHL app is down for tonight, try again tomorrow

**Comment by tlfs2222** [comment]
Is the NHL app still down?  Shows Streams available at game time but it is 6:45pm and there are no streams for the 6:00 and 6:30 games.

**Comment by jwallet** [comment]
still down, take a look at our subreddit for announcement: https://www.reddit.com/r/nhl_games/

**Comment by tlfs2222** [comment]
Thanks.  I appreciate the information.

**Comment by jwallet** [comment]
we were back the day after, closing the issue
