### ISSUE TITLE
No stream available

### ISSUE THREAD

**Issue by Nash442** [NHLGames/NHLGames#138]
![no stream](https://user-images.githubusercontent.com/34758523/34282323-74305120-e692-11e7-9fdd-d78e673fd752.png)

weird since yesterday, only one game with stream available, anybody else? solution? tks.

**Comment by jwallet** [comment]
NHLGames is down, got banned from NHL.com

**Comment by IanMSeattle** [comment]
So no more games through the player?  Bummer if true.

**Comment by NHLGames** [comment]
Back up (for now)
