### ISSUE TITLE
replay feature

### ISSUE THREAD

**Issue by jwallet** [NHLGames/NHLGames#149]
### game panel
- set X minutes behind live streams
- an option to restart a live game from the beginning gameStatusCode < streamEnded

### settings
- set the value of replay : minutes behind live stream
- game panel (on/off) option: All games behind live streams (using replay value)

**Comment by d-kar** [comment]
So, Is it possible to start watching game behind live stream? You thinking of passing some parameters to livestreamer?

**Comment by jwallet** [comment]
Yes it is possible with all players

**Comment by jwallet** [comment]
Related #151

**Comment by d-kar** [comment]
If only I knew it before, lol :)
The checkbox to start from the beginning is huge (at least for me)
I just checked yesterday '--hls-live-edge' livestreamer option and it works like a charm(need to figure out how to compute a number of segments though).
When you set to Output live stream it would dump already finished segments with the speed of your internet connection, so you can open that file and start fast-forwarding to the place where you want.
Previously I would have to start recording at the game start which is a pain. (not always have access to PC at that time)

**Comment by jwallet** [comment]
Segment = 12 every minute
So for 2h30 after game starts . 12 x 60 x 2.5 = 1800. Dont forget games starts 10 min after game time

**Comment by jwallet** [comment]
Btw which checkbox

**Comment by d-kar** [comment]
I'm not sure about the segment length.
Yesterday I was trying to start OTT-TOR game from the beginning when it was 9:20 pm. So 110 minutes from the 7:30 game start. 110 * 12 = 1320. That didn't quite work as stream started at the beginning of the first intermission. I multiplied by 2 and it started way behind the actual game start (about 55 minutes)
The 'checkbox' I mean, it would be a huge feature for me if checkbox to start game from start is implemented :)
