### ISSUE TITLE
Issue with All-Star game?

### ISSUE THREAD

**Issue by NHLGames** [NHLGames/NHLGames#156]
I think there might be an issue with parsing the schedule for Sunday (All-Star game).  Switching to that date gives this error:

`[10:00:57] Error: Code failed at: Running UI thread - With exception: System.NullReferenceException: Object reference not set to an instance of an object.`

**Comment by NHLGames** [comment]
Found the issue, it happens when there’s no team image.  Fix is already committed

**Comment by jwallet** [comment]
sure? my build is working fine and i get the default nhl icon if there is no team logo

**Comment by jwallet** [comment]
ok i tried 1.1.1.2 and i do get the same error. i dont know when i fixed it on my working branch.

**Comment by NHLGames** [comment]
Fixed in v1.1.1.3
