### ISSUE TITLE
Failed to Fetch Games Schedule

### ISSUE THREAD

**Issue by AlphaOmega912** [NHLGames/NHLGames#162]
When I open the program I get a message that says : 
Failure
No internet access! Make sure your antivirus did not delete a file or reinstall the app.  Do you want to exit NHLGames?

When I click no, the error Failed to Fetch Games Schedule pops up in the console.

Obviously it has something to do with my antivirus, but I have added the program to my safe list and reinstalled this program multiple times.

Any help would be appreciated.  Thank you.

The following is from the clipboard.

Operating system: Microsoft Windows 10 Home 64 Bits

Form: loaded, 0 games currently on form, Spinner (games) invisible 0/1000, Spinner (stream) invisible 0/1000

Servers: NHLGames IP found (nhl.freegamez.gq), NHL.TV redirection is working (Hosts file tested)

Selected player: VLC

Streamer path: C:\Users\Alpha\Desktop\NHLGames_v1.1.1.3\livestreamer\livestreamer.exe [on form] [exe found]

VLC path: D:\VLC\vlc.exe [on form] [exe found]

MPC path:  [on form] [exe not found]

MPV path: C:\Users\Alpha\Desktop\NHLGames_v1.1.1.3\mpv\mpv.exe [on form] [exe found]

Console log: 

[20:10:46] Status: Setting updated for 'MpcPath' to ''

[20:10:46] Status: Setting updated for 'SelectedLanguage' to 'English'

[20:10:46] Status: Setting updated for 'SelectedServer' to 'nhl.freegamez.gq'

[20:11:50] Fetching: Game schedule for 2018-02-07 from NHL.tv

[20:11:50] Status: Server http://statsapi.web.nhl.com/api/v1/schedule seems down

[20:11:50] Error: Failed to fetch games schedule.

**Comment by jwallet** [comment]
Any vpn or proxy? Can you access to the nhl.com api site in a web browser

**Comment by AlphaOmega912** [comment]
I do not have a VPN on this computer or my network.  I can access that
website, and if it helps I am still able to use the older version that I
have.  Version 1.1.0 if that would help you.

**Comment by jwallet** [comment]
same as #161
