### ISSUE TITLE
Custom host?

### ISSUE THREAD

**Issue by skaforey** [NHLGames/NHLGames#175]
My work blocks both hostnames in the app, but I can get to the data via IP....can we make an option to use strictly the IP or provide a different hostname?

**Comment by NHLGames** [comment]
Hmm, we might consider this in the future, in the meantime can you try this workaround and let me know if it works for you?  In your NHLGames directory open NHLGames.exe.Config with a text editor and look for this line:

`<add key="ServerList" value="freesports.ddns.net;freegamez.ga" />`

Then simply add the IP of our server to the list of choices:

`<add key="ServerList" value="freesports.ddns.net;freegamez.ga;188.240.208.152" />`

Save the file, and reopen NHLGames.  Under Settings, you should be able to pick the IP address as your hostname.

Let me know if you're able to stream using this config.

**Comment by jwallet** [comment]
the workaround might be enough to solve this issue. anyway this can be added at any time if this issue is too persistant
