### ISSUE TITLE
Playoff series lead shows even if 'Final Scores" is off

### ISSUE THREAD

**Issue by gourdo1** [NHLGames/NHLGames#186]
I always have "Final Score" disabled during the regular season so that the game's outcome isn't ruined for me when I watch several hours after the live broadcast. Similarly, it would be great if during the playoffs, there was a way to ensure the up-to-date series tally isn't disclosed before I start watching a game.

**Comment by jwallet** [comment]
turn off "series record"

**Comment by jwallet** [comment]
1bdeb3d16a027889dadaff5ba668b6adbe9cdeb3
