### ISSUE TITLE
MPV crashes when launched from NHLGames on 32 bits OS

### ISSUE THREAD

**Issue by Xyxy-** [NHLGames/NHLGames#194]
Hi there !

Firstly, thanks a lot for this invaluable tool. Hockey for everyone ! It is very user-friendly and well designed. I just love it !

I've remarked a difference of treatment between VLC and MPV in NHLGames. I wonder very much why it's different, I guess there is a good technical reason. Even though that's not the reason of this message, I'm curious to know actually... :smile: 

The difference is the following : with VLC, you can only follow the stream from beginning to end. But with MPV, you can jump to any time you would like. I'm interested in that feature, so I've been trying to replace VLC with MPV (I've had no problem with NHLGames/VLC).

I could not succeed however. I guess this is due to the fact that my OS is 32 bits (yeah, I do know that we're in 2018 :D ... But my 32 bits hardware still delivers!). Of course I understood that MPV provided by default is 64 bits - and it's normal. Therefore, I've been trying to use a separate 32 bits MPV installation but it also malfunctions. My observation is the following : I have approximately 0.1 sec of sound ("yay it works! \o/") while image hasn't come yet, then MPV crashes :neutral_face:.

I've used the last versions of NHL Games and MPV ; respectively 1.2.0.1 and 20171225.

I have no clue if it's a NHLGames issue, a MPV issue or an issue of the type "user did not *understand* how NHLGames and MPV interacts".

I've tried the following things :
- to use MPV in other contexts and it otherwise works flawlessly. That's the main reason why I post this message here.
- to use different streamers, to no avail. I doubt this is a streamer problem, because all streamers works with VLC and none works with MPV.

Does anyone have a clue ..?

I'd understand if people here were not fond of 32 bits problems, but at least I will have tried :D

Thanks in advance !

> mpv has stopped working - problem details
  Problem Event Name: APPCRASH
  Application Name: mpv.exe
  Application Version: 2.0.0.0
  Application Timestamp: 00000000
  Fault Module Name: msvcrt.dll
  Fault Module Version: 7.0.9600.17415
  Fault Module Timestamp: 54504b2e
  Exception Code: c0000005
  Exception Offset: 0000fe09
  OS Version: 6.3.9600.2.0.0.768.101
  Locale ID: 1036
  Additional Information 1: 5861
  Additional Information 2: 5861822e1919d7c014bbb064c64908b2
  Additional Information 3: 31c4
  Additional Information 4: 31c4f0c30ca267a761c69930266146b1

NHLGames log :

> [08:56:17] Starting: Streamer --player "C:\Program Files\mpv-i686-20171225\mpv.exe --force-window=immediate --title ""TOR @ BOS"" --user-agent=User-Agent=""Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36""  " --player-passthrough=hls  --http-header="User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36" "hlsvariant://[CENSORED_STREAM_URL] name_key=bitrate" best --http-no-ssl-verify 
[08:56:20] Streamer: found matching plugin stream for url hlsvariant://[CENSORED_STREAM_URL]
[08:56:21] Streamer: available streams: 1425k, 2121k, 2908k, 4023k, 559k (worst), 5772k (best), 985k
[08:56:21] Streamer: opening stream: 5772k (hls)
[08:56:21] Streamer: starting player: c:\program files\mpv-i686-20171225\mpv.exe --force-window=immediate --title "tor @ bos" --user-agent=user-agent="mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/63.0.3239.84 safari/537.36"

**Comment by jwallet** [comment]
we don't provide the 32 bits link for mpv, but this one should do
https://sourceforge.net/projects/mpv-player-windows/?source=typ_redirect
(automatic download)

**Comment by Xyxy-** [comment]
Ahah okay it does work with that MPV installation.

I don't understand how come MPV behaves differently whether I use your link or an official MPV link (https://mpv.io/installation/ -> https://mpv.srsfckn.biz/) to download it.

But whatever. Thanks a lot :smiley:
