### ISSUE TITLE
auto notify app after release

### ISSUE THREAD

**Issue by jwallet** [NHLGames/NHLGames#196]
in my other project i use a github trick to notify my users that my app has a new version out, it looks for tags version on github, so no need of an external file like version.

tell me if this is something you will like or you prefer to control the release with this file. because the down side is ,as soon as you published people will start to grab the version, even if it's a deleted release (except if the tag, as well, is deleted). but we can save new release to draft until it's ready to publish

**Comment by NHLGames** [comment]
I think this is a good idea, that way if I'm not around to update the server users can still see there is a new version available.

At the same time, you could remove the dependency of changelog.txt, so the only thing showtimes.ninja would be used for is announcement.txt.  There is not much room to show changes in the message box anyway, so it could just say to read about the changes on GitHub.

**Comment by jwallet** [comment]
announcement : https://api.github.com/repos/NHLGames/NHLGames/issues?state=open&labels=announcement
- title
- body

version : https://api.github.com/repos/NHLGames/NHLGames/releases
- tag_name
- body
- booleans: prerelease, draft
