### ISSUE TITLE
Feature/discussion: VOD spoiler prevention

### ISSUE THREAD

**Issue by tepsukka** [NHLGames/NHLGames#197]
Hi,

I live in a timezone where the games are usually very late, so I mostly watch them the day after from VODs. I'm wondering if there is a way to prevent spoilers when watching games from VODs. 

How this would be implemented I imagine is that maybe there is a flag for some/all of the video players that would allow you to set the duration manually, and then we would tell the player that the file is 3 hours in length, for example.

Another possibility I guess would be to somehow set a streaming flag that would make the length of the file unknown to the player.

A third option which comes to mind is to somehow add padding to the end of the file, but seems like it would be difficult to say the least.

What probably makes this feature even more complicated to implement would be support for all available players.

Just something I wanted to throw out there to discuss and see if there's any interest in something like this.

**Comment by d-kar** [comment]
There is a thread about this on reddit
https://www.reddit.com/r/nhl_games/comments/8cv3xz/how_to_avoid_spoilers/

Only for MPV though and I don't think there is a way to do it in MPC and VLC

**Comment by jwallet** [comment]
d-kar is right. and if you want to tweak mpv a bit more, you will find the manual [here](https://mpv.io/manual/master/), it's also included in the nhlgames_complete zip

**Comment by tepsukka** [comment]
That certainly is a decently viable way of hiding most of the spoiler information. Unfortunate that you have to sacrifice seeking and seeing how much of the file you have cached. Also it only works for MPV and not the other player options.

@jwallet I actually tried digging around the manual for a bit before posting this, and I found a "duration"  property in there. I tried to set it using the "set property" command, but it didn't seem to take. 

Maybe one possibility would be a flag or a setting in livestreamer? 

I would like to try and look for a way to do this. You can of course close this discussion if you feel like it and I can always re-open it if I find something.

**Comment by d-kar** [comment]
Seeking is not a problem using hot keys. Why would you want to see how much file you chached?
If you stream VODs as live stream then all seeking is gone, not sure why would you want this instead of original MPV solution.

**Comment by jwallet** [comment]
how about pressing `ctrl+h` when the stream opens in VLC, it will hide the status bar

**Comment by tepsukka** [comment]
@d-kar 
You are right, seeking is not a huge problem using the hotkeys. Sometimes streams freeze and connections are unstable, looking at the cache is a good way of knowing if you need to pause and let it buffer a little bit (not a big deal just a convenience). 

There is still however, a small problem even with the proposed solution of hiding the OSD. You can see the seek bar on your taskbar, at least on Windows 10 I can. [See this image](https://i.imgur.com/rBM5KFj.png), you can see a green bar indicating the amount the file has been played for.

Another problem I can think of is that if I pause or stop the stream for example at 1 hour, now I have pretty much no way of seeking back to that point when I restart, unless that spot is still saved in MPV's memory (I don't know exactly how it works).

@jwallet 
I just tested looking at a VOD with VLC and it looks like VLC doesn't even show the full length of the file, much less support seeking [see image here](https://i.imgur.com/awRNejh.png). So I think with VLC the spoiler problem is minimal. However the option you suggest is a solution if a file length is shown, this does once again mess with seeking though.

The best solution I have come up to so far with MPV has been to pass livestreamer this argument to enable HTTP streaming `--player-passthrough http`. 

MPV seems to work fairly well even with an HTTP stream. I can tell MPV to seek to around puck drop with `--start=08:00` although this takes a bit of time, maybe 10-30ish seconds. I can enable caching with `--cache=10240`, this allows me to see the the cache, and quickly seek within the cache. Seeks outside the cache are fairly fast as well although you can't seek more than a few seconds if the seek hits outside the cache. 

With this method you also eliminate the possibility of seeing the game progress from your taskbar (mostly) it will be very hard to deduce when the game is actually ending because there is a couple minutes of padding at the end of games, so unless you're looking at your cache and see that it's not filling anymore, you should'nt be able to tell.

**Comment by jwallet** [comment]
since this issue is not related to nhlgames, im gonna close it
