### ISSUE TITLE
Task: Add mitmproxy to remove hosts file edit

### ISSUE THREAD

**Issue by NHLGames** [NHLGames/NHLGames#200]
Adding this here as a reminder for myself :)

Need to add mitmproxy (https://github.com/mitmproxy/mitmproxy) to match LazyMan's new beta:

https://www.reddit.com/r/LazyMan/comments/8i8dwf/24_beta/

This way there is no longer a need to edit the hosts file and we can point to a domain instead of an IP (can use cloudflare, more anonymous)

-mitmdump.exe needs to launch when the app starts
-streamlink needs to set proxy param https://streamlink.github.io/cli.html#proxy-support
-because of the hls passthrough, mpv needs its own proxy environment variable set https://github.com/mpv-player/mpv/issues/3373

**Comment by jwallet** [comment]
if you have to use other streamer command make sure that you take those that are also available on livestreamer, before using any streamlink commands, we still support livestreamer
http://docs.livestreamer.io/cli.html#cmdoption-https-proxy

**Comment by NHLGames** [comment]
Crap, accidentally committed to master instead of my branch (I suck at git lol)

This is mostly done, but it's missing code to wait for the proxy to start (if you look at Console you see it takes a few seconds to run.  If someone clicks on a game too fast they will get an error)

**Comment by jwallet** [comment]
just went on master to see what you committed, i don't see why you had to switch back to streamlink since livestreamer works fine on my side. so the app can still support both streamers. i saw some wip code in there, so i added todos to some lines, i can still work on it a bit

**Comment by NHLGames** [comment]
Weird, for some reason the stream would not start when I ran with livestreamer.  I'll have to give it another try.  I think the main change that is missing is modifying the spinner animation to not show games until the proxy is started

**Comment by jwallet** [comment]
i have done it on my branch

**Comment by jwallet** [comment]
chrome blacklisted the zip file, the app is now flagged as malware, not a good thing for the average user
