### ISSUE TITLE
[Task] refact the Spotify Addon to make it work after Spotify last update

### ISSUE THREAD

**Issue by jwallet** [NHLGames/NHLGames#204]
Spotify updated the way they handle the authentification, so now the local API does not work anymore, so the Spotify module is affected by this update, all queries won't work until further explanation how to get a token from Spotify or find another way to control Spotify app because maybe they don't send any token anymore

**Comment by NHLGames** [comment]
Hmm that's weird, Spotify is currently working for me - version 1.0.89.313.g34a58dea (Windows Store version)

Is this an older version than the latest available?

**Comment by jwallet** [comment]
i'm sure it won't work since spotify closed the local api this summer, we can't get a valid auth token anymore
