### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Codehhh** [NHLGames/NHLGames#21]
Not sure what changed from the last push, but I can no longer build from source. When I try to build I get roughly 50 errors of

>"... could not be found (are you missing a using directive or an assembly reference?)"

Using Visual Studio Community 2015 Version 14.0.25123.00 Update 2

**Comment by NHLGames** [comment]
That's very strange, it still works for me.  Only difference is I haven't installed Update 2 yet.

**Comment by Codehhh** [comment]
Found the issue! I think you removed the packages folder from git. It contains all of the DLLs needed!

**Comment by NHLGames** [comment]
Weird, I don't remember removing anything, but maybe the sync messed it up
