### ISSUE TITLE
Can't find the specified streamer error

### ISSUE THREAD

**Issue by reaktorblue** [NHLGames/NHLGames#220]
**Describe the bug**
[18:59:21] Error:  Can't find the specified streamer. The streamer is used to send streams to your media player, please select the one that comes with NHLGames or select a valid path of Livestreamer.exe or Streamlink.exe

_Note_ - This error is not present on version 1.3.2 Complete and everything is working successfully on version 1.3.2 Complete.

**To Reproduce**
1. Open NHL Games 1.3.2.2 Complete
2. Click on MSG for FLA vs NYR game on 10/23/18 at 7:00 PM EST
3. Receive error message

**Expected behavior**
It's expected that the stream starts and the game is able to be watched.

**Console log**
NHLGames Bug Report v 1.3.2.2

Operating system: Microsoft Windows 7 Ultimate  64 Bits - .Net build 4.0.30319.42000	
Internet: Connection test succeeded, ping google.com succeeded	
Form: loaded, 8 games currently on form, Selected player: MPV	
Streamer path:  [on form] [exe not found]	
VLC path: C:\Program Files (x86)\VideoLAN\VLC\vlc.exe [on form] [exe found]	
MPC path: C:\Users\Reaktorblue\Dropbox\Project - Portable\PortableApps\MPC-HCPortable\App\MPC-HC\mpc-hc.exe [on form] [exe found]	
MPV path: C:\Users\Reaktorblue\Downloads\NHLGames-v1.3.2.2-complete\mpv\mpv.exe [on form] [exe found]

Console log: 	
[19:05:26] Error:  Can't find the specified streamer. The streamer is used to send streams to your media player, please select the one that comes with NHLGames or select a valid path of Livestreamer.exe or Streamlink.exe

**Screenshots**
If applicable, add some screenshots to help explain your problem.

**Comment by jwallet** [comment]
set the streamer path, the streamer is provided in the streamlink folder

**Comment by reaktorblue** [comment]
That resolved the issue, thanks!

**Comment by jwallet** [comment]
i updated the package https://github.com/NHLGames/NHLGames/releases/tag/v1.3.2.2
