### ISSUE TITLE
--player-passthrough=hls does not work

### ISSUE THREAD

**Issue by NHLGames** [NHLGames/NHLGames#23]
Passing this parameter to livestreamer (to enable seeking in VODs) makes VLC or MPC not able to read the video stream.

If you open the VLC message, console it seems it is running into a 504 gateway time-out.

**Comment by NHLGames** [comment]
Update: mpv supports this, and can even play the hls stream directly.

**Comment by d-kar** [comment]
How to use mpv with NHLGames? New update coming soon?

**Comment by NHLGames** [comment]
Hey,

Yup I'm hoping to release a new update this week :) I just wrote this as a note to myself haha

**Comment by d-kar** [comment]
Any thoughts on PVR functionality? Would be nice if in progress game could be started from the beginning and fast forwarded during commercial break/intermissions.
Right now I have to open app when the game starts and output stream to the file, then load file once I'm ready to watch.

**Comment by NHLGames** [comment]
Yup mpv will support this as well!

**Comment by NHLGames** [comment]
Fixed in latest release (using mpv player).
