### ISSUE TITLE
Error still happening - When Game Stream selected - Error No Media Player selected in Settings.

### ISSUE THREAD

**Issue by keithcrogers** [NHLGames/NHLGames#233]
Already reported this a few days ago under v.4 .  Same error occurring after doing complete download/reinstall of v.5 .  Thought maybe the updated v5 would fix, but still same.  Of course, my settings have a designated Media Player, even tried trying different media player selections.  All same result with this error:

NHLGames Bug Report v 1.3.2.5

Operating system: Microsoft Windows 10 Home 64 Bits - .Net build 4.0.30319.42000	
Internet: Connection test succeeded, ping google.com succeeded	
Streamer args enabled: --hls-segment-threads=2 --hls-segment-attempts=10 --hls-segment-timeout=60	
Player args enabled: --file-caching=10000 --network-caching=10000 --cache=50000	
Selected player: MPV	
Streamer path:  [not on form] [exe not found]	
VLC path:  [not on form] [exe not found]	
MPC path:  [on form] [exe not found]	
MPV path:  [not on form] [exe not found]

Console log: 	
[20:34:41] Warning: Failed to write app settings	
[20:34:41] Warning: Failed to write app settings	
[20:34:41] Warning: Failed to write app settings	
[20:34:41] Warning: Failed to write app settings	
[20:34:41] Warning: Failed to write app settings	
[20:34:41] Warning: Failed to write app settings	
[20:34:41] Warning: Failed to write app settings	
[20:34:41] Warning: Failed to write app settings	
[20:34:41] Warning: Failed to write app settings	
[20:34:41] Warning: Failed to write app settings	
[20:34:41] Warning: Failed to write app settings	
[20:34:41] Status: Setting updated for 'HOSTNAME' to 'freegamez.ga'	
[20:34:41] Warning: Failed to write app settings	
[20:34:41] Warning: Failed to write app settings	
[20:34:41] Warning: Failed to write app settings	
[20:34:41] MLBAMProxy: Proxy is getting ready	
[20:34:41] MLBAMProxy: Proxy server listening on port: 17070	
[20:34:42] Fetching: Game schedule for 2019-01-14 from NHL.tv	
[20:34:48] Error: No media player selected in settings.

**Comment by jwallet** [comment]
if you want to fix it right away, edit the `nhlgames.exe.config` file with notepad, at the line `9` paste this line
```
<add key="DefaultWatchArgs" value="&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&#xD;&#xA;&lt;GameWatchArguments xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&#xD;&#xA;  &lt;GameDate&gt;2019-01-14T22:14:10.4831538-05:00&lt;/GameDate&gt;&#xD;&#xA;  &lt;Quality&gt;_224p&lt;/Quality&gt;&#xD;&#xA;  &lt;Is60Fps&gt;false&lt;/Is60Fps&gt;&#xD;&#xA;  &lt;Cdn&gt;Akc&lt;/Cdn&gt;&#xD;&#xA;  &lt;GameTitle /&gt;&#xD;&#xA;  &lt;PlayerPath&gt;c:\Program Files (x86)\VideoLAN\VLC\vlc.exe&lt;/PlayerPath&gt;&#xD;&#xA;  &lt;PlayerType&gt;Vlc&lt;/PlayerType&gt;&#xD;&#xA;  &lt;StreamerPath&gt;D:\dev\NHLGames\bin\Debug\streamlink\streamlink.exe&lt;/StreamerPath&gt;&#xD;&#xA;  &lt;UseCustomStreamerArgs&gt;true&lt;/UseCustomStreamerArgs&gt;&#xD;&#xA;  &lt;CustomStreamerArgs&gt; --hls-segment-threads=4 --hls-segment-attempts=10 --hls-segment-timeout=60&lt;/CustomStreamerArgs&gt;&#xD;&#xA;  &lt;UseCustomPlayerArgs&gt;true&lt;/UseCustomPlayerArgs&gt;&#xD;&#xA;  &lt;CustomPlayerArgs&gt; --file-caching=10000 --network-caching=10000&lt;/CustomPlayerArgs&gt;&#xD;&#xA;  &lt;UseOutputArgs&gt;false&lt;/UseOutputArgs&gt;&#xD;&#xA;  &lt;PlayerOutputPath /&gt;&#xD;&#xA;  &lt;StreamLiveRewind&gt;5&lt;/StreamLiveRewind&gt;&#xD;&#xA;  &lt;GameIsOnAir&gt;false&lt;/GameIsOnAir&gt;&#xD;&#xA;  &lt;StreamLiveReplayCode&gt;Live&lt;/StreamLiveReplayCode&gt;&#xD;&#xA;  &lt;StreamerType&gt;StreamLink&lt;/StreamerType&gt;&#xD;&#xA;  &lt;StreamLiveReplay&gt;PuckDrop&lt;/StreamLiveReplay&gt;&#xD;&#xA;&lt;/GameWatchArguments&gt;" />
```

but i'm pretty sure the warning message is your bug, your system does not let NHLGames edit its own file `nhlgames.exe.config`, set the proper rights in properties>settings of the file

**Comment by jwallet** [comment]
[latest version](https://github.com/NHLGames/NHLGames/releases/latest) should keep the settings in memory if it fails to write app settings to appData folder, can you give it a try?
