### ISSUE TITLE
Settings Not Saving 

### ISSUE THREAD

**Issue by teamcoltra** [NHLGames/NHLGames#235]
**Describe the bug**
in version v1.3.2.5 complete settings do not save after restarting.

**To Reproduce**
If applicable, enumerate the steps to reproduce the bug:
1. Download v1.3.2.5
2.  Make settings
3.  Restart
4. ???
5. No profit NOR the settings are saved :(

**Comment by krevan88** [comment]
I am also having this issue. Same steps and everything.

**Comment by jwallet** [comment]
![test](https://user-images.githubusercontent.com/23088305/52455935-9deccb00-2b20-11e9-8d4f-7d3db115fd8b.gif)

**Comment by jwallet** [comment]
already solved in 1.3.3
