### ISSUE TITLE
buffering issue while watching a game on TV over wifi

### ISSUE THREAD

**Issue by Benkellie** [NHLGames/NHLGames#238]
**Hello. I would like to have your help on NHLStream. When I listen to it with my 27 inch computer monitor, all is fine but if I plug my computer to my 65 inch TV, NHL Stream does not work well and im using MPV player.

So can you help me? Thank you and excuse my english, I help with Google**

**Comment by jwallet** [comment]
NHLGames marche pas bien, que veux tu dire?

**Comment by Benkellie** [comment]
Ah salut je peux mieux m'exprimer en français.... 

Donc, mon problème je pense que tous tourne a la résolution de lecrant et je ne comprend pas pourquoi ..... 

Je m'explique, si j'ouvre nhlstream avec mon moniteur ( écrant ) d'ordinateur 27 pouce, il y a rien qui bogue je peux regarder une partie de hockey parfaitement. 
MAIS 
Si je branche ma tour d'ordinateur a ma télévision 65 pouce, rien ne va bien. Les match que je choisie bogue au 10 secondes et ses pareille si j'essaie de regarder une partie de hockey en streaming sur le web. 

Alors aurais tu une explication pour moi s'il te plaît parce-que je suis a bout, je ne comprend pas du tous le pourquoi du comment.

**Comment by jwallet** [comment]
est ce que tu deplace ton ordinateur pour le brancher a ta tv, j'imagine qu'une raison pourrait etre la connectivite de ton Internet, la vitesse est pas prioritaire mais le fait d'etre connecter a fil est mieux que par wifi. la resolution ou changer d'ecran ne devrait rien avoir avec le fait que le stream termine trop tot. donc non j'ai pas d'autres explications.

**Comment by Benkellie** [comment]
Oui je la déplace et j'ai connecté ma tour a un petite plug wifi qui ce branche dans le USB. 
Quand tu regarde un match de hockey sur nhlstream, en bas de ton écrant il y a une ligne noir qui se prolonge plus le stream avance right ? Ensuite tu a autre chose qui avance et qui suit la ligne noir mais moi le problème ses que cette fameuse ligne noir avant pas assez vite alors les deux se rattrape et ainsi sa créé un gel et sa recommence ainsi de suite. J'ai trouver une solution, j'ouvre un match et j'attend 5 minutes que sa.charge et je commence le.regarder. mais reste que je comprend pas pourquoi cette ligne noir là ne charge pas assez vite ?

**Comment by jwallet** [comment]
c'est le buffer, c'est ta connexion internet

**Comment by Benkellie** [comment]
D'accord, et je fais comment pour améliorer ça ? Stp

**Comment by jwallet** [comment]
- reste connecte avec un fil au router;
- utilise une moins haute qualite de stream 420p par exemple
- utilise la fonction [rewind] de 15 minutes par les [settings](https://github.com/NHLGames/NHLGames#rewind-and-replay) pour avoir un meilleur buffer sur les parties en direct,
- utilise un service de stream sur le net
- essaie lazyman
- essaie la v1.3.0 de nhlgames

**Comment by Benkellie** [comment]
Ok merci beaucoup pour ton Aide. C'est grandement apprécié.
Et petite question comme ça, aujourd'hui 18 Mars, AUCUN stream est disponible sur nhlstream ses tu normal et sa arrive tu souvent ?.

**Comment by Benkellie** [comment]
Salut. Je vien de recevoir ce message la sur nhlstream sa rapport a quois ? 

<data name="errorMitmProxyNotFound" xml:space="preserve">
<value>Error: Can't find mitmproxy : mitmproxy is a https proxy that we shipped with NHLGames. You probably moved it or deleted it. Please go to our GitHub page to get it back, NHLGames needs it</value>

**Comment by jwallet** [comment]
#240
