### ISSUE TITLE
Error on startup -  Operation did not complete successfully because the file contains a virus or potentially unwanted software

### ISSUE THREAD

**Issue by Stoldney** [NHLGames/NHLGames#239]
I just got this error tonight (3/19). I was streaming the Stars v Panthers game on my laptop just fine, then switched to my PC. On the PC this error happens, even though it was working fine just 5 mins ago:

NHLGames Bug Report v 1.3.3.0

Operating system: Microsoft Windows 10 Pro 64 Bits - .Net build 4.0.30319.42000	
Internet: Connection test succeeded, ping google.com succeeded	
Streamer args enabled:--hls-segment-threads=4 --hls-segment-attempts=30 --hls-segment-timeout=60	
Player args enabled:--file-caching=10000 --network-caching=10000	
Selected player: VLC	
Streamer path: C:\Users\anoth\Desktop\NHLGames\1.3.3\streamlink\streamlink.exe [on form] [exe found]	
VLC path: C:\Program Files\VideoLAN\VLC\vlc.exe [on form] [exe found]	
MPC path: C:\Program Files\MPC-HC\mpc-hc64.exe [on form] [exe found]	
MPV path: C:\Users\anoth\Desktop\NHLGames\1.3.3\mpv\mpv.exe [on form] [exe found]

Console log: 	
[20:35:36] Status: Setting updated for 'HOSTNAME' to 'freegamez.ga'	
[20:35:36] MLBAMProxy: Proxy is getting ready	
[20:35:37] Fetching: Game schedule for 2019-03-19 from NHL.tv	
[20:35:38] Error: Code failed at: Starting proxy - With exception: Operation did not complete successfully because the file contains a virus or potentially unwanted software

For grins, I closed the app and re-opened it. Different error this time:

NHLGames Bug Report v 1.3.3.0

Operating system: Microsoft Windows 10 Pro 64 Bits - .Net build 4.0.30319.42000	
Internet: Connection test succeeded, ping google.com succeeded	
Streamer args enabled:--hls-segment-threads=4 --hls-segment-attempts=30 --hls-segment-timeout=60	
Player args enabled:--file-caching=10000 --network-caching=10000	
Selected player: VLC	
Streamer path: C:\Users\anoth\Desktop\NHLGames\1.3.3\streamlink\streamlink.exe [on form] [exe found]	
VLC path: C:\Program Files\VideoLAN\VLC\vlc.exe [on form] [exe found]	
MPC path: C:\Program Files\MPC-HC\mpc-hc64.exe [on form] [exe found]	
MPV path: C:\Users\anoth\Desktop\NHLGames\1.3.3\mpv\mpv.exe [on form] [exe found]

Console log: 	
[20:41:45] Status: Setting updated for 'HOSTNAME' to 'freegamez.ga'	
[20:41:45] MLBAMProxy: Proxy is getting ready	
[20:41:45] Error: Can't find mitmproxy : mitmproxy is a https proxy that we shipped with NHLGames. You probably moved it or deleted it. Please go to our GitHub page to get it back, NHLGames needs it	
[20:41:47] Fetching: Game schedule for 2019-03-19 from NHL.tv

This error now happens on every start. No changes have been made to the installation.

**Comment by jwallet** [comment]
you need to whitelist the app and mitmproxy app that comes with the app, your security software removed it. if you don't want to whitelist the proxy you may use go-mlbam-hosts available in the release page https://github.com/NHLGames/NHLGames/releases to create a redirection url
