### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by Womper204** [NHLGames/NHLGames#240]
Works fine on my PC but on my wives computer I get this error when starting the program

NHLGames Bug Report v 1.3.3.0

Operating system: Microsoft Windows 10 Home 64 Bits - .Net build 4.0.30319.42000	
Internet: Connection test succeeded, ping google.com succeeded	
Streamer args enabled:--hls-segment-threads=4 --hls-segment-attempts=30 --hls-segment-timeout=60	
Player args enabled:--cache=50000	
Selected player: MPV	
Streamer path: E:\NHL\streamlink\streamlink.exe [on form] [exe found]	
VLC path: C:\Program Files\VideoLAN\VLC\vlc.exe [on form] [exe found]	
MPC path:  [on form] [exe not found]	
MPV path: E:\NHL\mpv\mpv.exe [on form] [exe found]

Console log: 	
[18:22:53] Status: Setting updated for 'HOSTNAME' to 'freegamez.ga'	
[18:22:53] MLBAMProxy: Proxy is getting ready	
[18:22:53] Error: Can't find mitmproxy : mitmproxy is a https proxy that we shipped with NHLGames. You probably moved it or deleted it. Please go to our GitHub page to get it back, NHLGames needs it	
[18:22:55] Fetching: Game schedule for 2019-03-20 from NHL.tv
1.3.3.0
1.3.3.0

So the actual error on the screen is 

[18:22:53] Error: Can't find mitmproxy : mitmproxy is a https proxy that we shipped with NHLGames. You probably moved it or deleted it. Please go to our GitHub page to get it back, NHLGames needs it	

To further clarify, I downloaded the newest version, moves the files to my desktop and it worked fine. Transferred the files to a usb stick and dragged them to the other computer and it doesn't work. Any ideas?

**Comment by wrhammer** [comment]
Getting the same: Can't find mitmproxy : mitmproxy is a https proxy that we shipped with NHLGames.

**Comment by jwallet** [comment]
i should fix the message, but it looks like. like the log says, your security software removed the proxy that we added to the zip file. `/mlbamproxy/x64~x86/mlbamproxy.exe` should be there

**Comment by Habmania** [comment]
I am having exact same issue. Mcafee antivirus is physically removing the file in the mlbamproxy x64 folder.  I assume there is no virus in the file? We can add exceptions in the antivirus settings.

**Comment by jwallet** [comment]
it's normal for an antivirus to remove a proxy that redirect every url X (in this case nhl) to another url Y (in this case us), it's common out there that people will make a mitmproxy that redirect, for example, facebook or paypal to a fake website with the same name to get your info. but in our case it's safe to use.

**Comment by Womper204** [comment]
I'm just using Windows defender as well as the other computer. Why would it work on mine and not the other though even after just transferring it via USB?

**Comment by jwallet** [comment]
@Womper204 do you still have mlbamproxy.exe in the folder ?

**Comment by jwallet** [comment]
closing, looks like the proxy just needs to be whitelisted
