### ISSUE TITLE
FYI - Windows Defender flagging mlbamproxy.exe as trojan

### ISSUE THREAD

**Issue by joeshlabotnik** [NHLGames/NHLGames#241]
FYI -  Windows Defender is quarantining ...mlbamproxy\x64\mlbamproxy.exe saying it's the Win32/Zpevdo.B trojan and then NHLGames won't start

Using latest release. 1.3.2.5  Downgraded to 1.3.2.4 and it's not flagging it anymore.

This just started happening - I've been using 1.3.2.5 for several weeks.

**Comment by jwallet** [comment]
move it out of quarantining
mlbamproxy is a revert proxy only for nhl.tv domain
you can see the source code here [on github](https://github.com/jwallet/go-mlbam-proxy)
