### ISSUE TITLE
mpv no longer opening

### ISSUE THREAD

**Issue by Plut0nio** [NHLGames/NHLGames#253]
I recently updated Streamlink, mpv, and NHLGames to their latest versions (Windows 10 64-bit) recently. Since I upgraded mpv (May 19 shinchiro build), however, mpv no longer opens whenever I select a stream. The [console output](https://github.com/NHLGames/NHLGames/files/3225332/NHLGames_Log.txt) gets stuck at "Streamer: starting player: c:\program files\mpv\mpv.exe" and nothing happens. I don't see mpv.exe or streamlink.exe in the "Details" tab of Task Manager. I installed the newest version of VLC (3.0.6) and that actually opened up the streams from NHLGames just fine, with vlc.exe and streamlink.exe both appearing in the Task Manager "Details" tab. Opening up my own video files with mpv works fine, and so does opening up a Twitch stream, for example, using Streamlink in the command line. I'm not sure what could be the culprit here: NHLGames, mpv, or Streamlink.

**Comment by jwallet** [comment]
try using the one provided in the nhlgames zip archive

**Comment by Plut0nio** [comment]
> 
> 
> try using the one provided in the nhlgames zip archive

This does the trick! The mpv build included in the zip was built on Feb 17 (mpv 0.28.0-285-g0dbad9503f). I guess it's a problem with mpv, then. I think I'll let shinchiro and the mpv team know about this. Thanks.
