### ISSUE TITLE
Error: Code failed at: Starting proxy - With exception: The system cannot find the file specified

### ISSUE THREAD

**Issue by BangMePlz** [NHLGames/NHLGames#255]
**Describe the bug**

Getting an error on app start up.

**Console log**

NHLGames Bug Report v 1.4.1.0

Operating system: Microsoft Windows 7 Ultimate  64 Bits - .Net build 4.0.30319.42000	
Internet: Connection test succeeded, ping google.com succeeded	
Streamer args enabled:--hls-segment-threads=2 --hls-segment-attempts=9 --hls-segment-timeout=10 --hls-timeout=180	
Player args enabled:--file-caching=10000 --network-caching=10000	
Selected player: VLC	
Streamer path: C:\Users\Bedroom\Downloads\NHLGames-v1.4.1-complete\streamlink\streamlink.exe [on form] [exe found]	
VLC path: C:\Program Files\VideoLAN\VLC\vlc.exe [on form] [exe found]	
MPC path: C:\Program Files\MPC-HC\mpc-hc64.exe [on form] [exe found]	
MPV path: C:\Users\Bedroom\Downloads\NHLGames-v1.4.1-complete\mpv\mpv.exe [on form] [exe found]

Console log: 	
[18:22:53] Status: Setting updated for 'HOSTNAME' to 'freegamez.ga'	
[18:22:53] Error: Code failed at: Starting proxy - With exception: The system cannot find the file specified	
[18:22:55] Fetching: Game schedule for 2019-10-02 from NHL.tv

I have run many other versions without issue. I just downloaded this version.

**Comment by NICKCHEESE** [comment]
Make sure your antivirus isn't blocking the application. I was getting this same exact error and saw my AV was blocking the proxy service. Added the folder to my exceptions and now it's working perfectly.

**Comment by spazmcnasty** [comment]
I am having the same issue, no AV outside of the builtin windows 10

**Comment by BangMePlz** [comment]
> Make sure your antivirus isn't blocking the application. I was getting this same exact error and saw my AV was blocking the proxy service. Added the folder to my exceptions and now it's working perfectly.

AV was the problem. Thank you.

> I am having the same issue, no AV outside of the builtin windows 10

After adding the exclusion/exception I extracted the zip folder files again to make sure I had all the files my AV deleted and it worked.

**Comment by spazmcnasty** [comment]
> After adding the exclusion/exception I extracted the zip folder files again to make sure I had all the files my AV deleted and it worked.

Ahhhh Perfect thank you. Works.
