### ISSUE TITLE
No scaling for 4k resolution

### ISSUE THREAD

**Issue by itsREV** [NHLGames/NHLGames#256]
The UI doesn't scale appropriately with 4k windows resolution

I am currently running my computer on my 4k TV and noticed that when windows was set to 1920x1080 UI is scaled normally but when switched to 4k resolution the UI stays extremely small and hard to use.

**Console log**
NHLGames Bug Report v 1.4.1.0

Operating system: Microsoft Windows 10 Pro 64 Bits - .Net build 4.0.30319.42000	
Internet: Connection test succeeded, ping google.com succeeded	
Streamer args enabled:--hls-segment-threads=2 --hls-segment-attempts=9 --hls-segment-timeout=10 --hls-timeout=180	
Player args enabled:--cache=50000	
Selected player: MPV	
Streamer path: E:\nhl\NHLGames-v1.4.1-complete\streamlink\streamlink.exe [on form] [exe found]	
VLC path: C:\Program Files\VideoLAN\VLC\vlc.exe [on form] [exe found]	
MPC path:  [on form] [exe not found]	
MPV path: E:\nhl\NHLGames-v1.4.1-complete\mpv\mpv.exe [on form] [exe found]

Console log: 	
[21:26:23] Status: Setting updated for 'HOSTNAME' to 'freegamez.ga'	
[21:26:23] MLBAMProxy: Proxy version 1.1.1 is getting ready	
[21:26:23] MLBAMProxy: Proxy server listening on port: 17070	
[21:26:24] Fetching: Game schedule for 2019-10-03 from NHL.tv

**Screenshots**
not maximized

![image](https://user-images.githubusercontent.com/21894233/66176811-c0d66d00-e624-11e9-9b34-20a680833866.png)

maximized
![image](https://user-images.githubusercontent.com/21894233/66177026-6558af00-e625-11e9-9276-577d08740dc8.png)

**Comment by jwallet** [comment]
you have this topic in our wiki https://github.com/NHLGames/NHLGames/wiki/app-not-rendering-well#-appears-too-small----change-the-dpi-settings-in-nhlgamesexe-properties
