### ISSUE TITLE
issue with app starting

### ISSUE THREAD

**Issue by wichita13** [NHLGames/NHLGames#259]
NHLGames Bug Report v 1.4.1.0

Operating system: Microsoft Windows 10 Home 64 Bits - .Net build 4.0.30319.42000	
Internet: Connection test succeeded, ping google.com succeeded	
Streamer args enabled:--hls-segment-threads=2 --hls-segment-attempts=9 --hls-segment-timeout=10 --hls-timeout=180	
Player args enabled:--file-caching=10000 --network-caching=10000	
Selected player: VLC	
Streamer path: C:\Users\ninmug\Documents\NHLGames-v1.4.1-complete (3)\streamlink\Streamlink.exe [on form] [exe found]	
VLC path: C:\Program Files (x86)\VideoLAN\VLC\vlc.exe [on form] [exe found]	
MPC path: C:\Program Files\MPC-HC\mpc-hc64.exe [on form] [exe found]	
MPV path: C:\Users\ninmug\Documents\NHLGames-v1.4.1-complete (3)\mpv\mpv.exe [on form] [exe found]

Console log: 	
[15:11:45] Status: Setting updated for 'HOSTNAME' to 'freesports.ddns.net'	
[15:11:45] Error: Code failed at: Starting proxy - With exception: The system cannot find the file specified	
[15:11:46] Fetching: Game schedule for 2019-10-11 from NHL.tv

**Expected behavior**
If applicable, describe what you expect to happen.

**Console log**
Please, paste here the console log of the app, click on `copy to clipboard` in settings.

**Screenshots**
If applicable, add some screenshots to help explain your problem.

**Comment by jwallet** [comment]
re download the zip file or unzip it again, looks like your antivirus deleted it from the folder. you can also run `go-mlbam-hosts` available [here](https://github.com/NHLGames/NHLGames/releases) to use the windows hosts file instead of the proxy
