### ISSUE TITLE
Set default filename when choosing Output option (e.g. BOS - CBJ 2016-20-13.mp4)

### ISSUE THREAD

**Issue by NHLGames** [NHLGames/NHLGames#27]
See related reddit post:

https://www.reddit.com/r/nhl_games/comments/57ego3/request_allow_us_to_select_output_folder_and_have/

**Comment by d-kar** [comment]
Also, include quality and home/away/national/french type.

**Comment by d-kar** [comment]
Pull request #35 implements this

**Comment by NHLGames** [comment]
Yep it does, I will include it once I release the next version at some point this week.
