### ISSUE TITLE
Updated to 1.4.2, still presented as 1.4.1

### ISSUE THREAD

**Issue by murko69** [NHLGames/NHLGames#270]
I downloaded the NHLGames-v1.4.2-simplified.zip, copied all the files and pasted over my previous files.
Then when starting the app for the first time after updating to 1.4.2, the first thing I got was a "there's an update avaliable" -screen
Then the app still shows 1.4.1 in the bottom left corner.

However - the games fråm Aug. 1 and ahead is coming up fine (the app got stuck yesterday) so I do think it's updated correctly and this is just a presentation thing - "cache issue" of sorts?

**Comment by NHLGames** [comment]
I uploaded a dud version and fixed it an hour or 2 later - did you try re-downloading the file?

**Comment by murko69** [comment]
Never tried that til' now and yoiu are correct!
This time it's also presented in the right way - Closing the issue.
Thanks. Can't wait for the season to re-start!
