### ISSUE TITLE
Draging the window around is buggy

### ISSUE THREAD

**Issue by StormACE** [NHLGames/NHLGames#272]
**Describe the bug**
If your title may be unclear, add a clear and concise description of what the bug is.
Draging the window around is kinda weird hope you can see this

**To Reproduce**
If applicable, enumerate the steps to reproduce the bug:
1.just drag the window around
2. 
3. 

**Expected behavior**
If applicable, describe what you expect to happen.
dragging should be fluid

**Console log**
Please, paste here the console log of the app, click on `copy to clipboard` in settings.

**Screenshots**
If applicable, add some screenshots to help explain your problem.

**Comment by jwallet** [comment]
your issue might be related to dpi issue, if you have a monitor with higher resolution or pixel ratio than the other one. so change the exe dpi scale setting like so 
https://github.com/NHLGames/NHLGames/wiki/app-not-rendering-well#-appears-too-small----change-the-dpi-settings-in-nhlgamesexe-properties
