### ISSUE TITLE
Minimize, Maximize and Close icons are not rendering properly.

### ISSUE THREAD

**Issue by cracklejoy** [NHLGames/NHLGames#273]
**Describe the bug**
The minimize, maximize and close icons are not rendering properly in upper right of application window.  Buttons are functional but the proper icons are not being displayed.

**To Reproduce**
Start the application.

**Expected behavior**
Proper icons should be present.

Application being run on a standard Windows 10 install.  Never seen this issue on any other installed applications.

**Screenshots**
<img width="495" alt="nhlgames_min_max_close_icons_issue" src="https://user-images.githubusercontent.com/65365730/89718361-c959ab80-d98b-11ea-912c-53732d79d7c2.png">

**Comment by jwallet** [comment]
normally affected by a change in your Windows 10 settings, like screen pixel sizing DPI. The app does not support DPI Scale and High Contrast mode

https://github.com/NHLGames/NHLGames/wiki/app-not-rendering-well
