### ISSUE TITLE
App claims "no internet access!" on startup, otherwise functions fine

### ISSUE THREAD

**Issue by Sorator** [NHLGames/NHLGames#276]
When I open the app, I get the "no internet access! Exit NHLGames?" error popup, but if I say "no" and continue to the games list, it loads just fine, so it clearly _does_ have internet access. Tried downloading & extracting the latest release again (overwriting files with the same name, ofc) and the issue was unchanged; tried doing it again with antivirus (Webroot) disabled, and again no change. Likewise, tried changing the port on the off chance that would matter, but no change. Any thoughts? It's not critical, since things still work (though I haven't tried actually watching a game yet it seems like it _should_ work), it's just mildly annoying.

**Console log**
NHLGames Bug Report v 1.4.2.0

Operating system: Microsoft Windows 10 Home 64 Bits - .Net build 4.0.30319.42000	
Internet: Connection test succeeded, ping google.com failed	
Streamer args enabled:--hls-segment-threads=2 --hls-segment-attempts=9 --hls-segment-timeout=10 --hls-timeout=180	
Player args enabled:--cache=50000	
Selected player: MPV	
Streamer path: E:\Program Files (x86)\NHLGames\livestreamer\livestreamer.exe [on form] [exe found]	
VLC path:  [on form] [exe not found]	
MPC path:  [on form] [exe not found]	
MPV path: E:\Program Files (x86)\NHLGames\mpv\mpv.exe [on form] [exe found]

Console log: 	
[14:28:15] Status: Setting updated for 'HOSTNAME' to 'freegamez.ga'	
[14:28:15] MLBAMProxy: Proxy version 1.1.1 is getting ready	
[14:28:15] MLBAMProxy: Proxy server listening on port: 16030	
[14:28:18] Status: No Internet access!	
[14:28:18] Fetching: Game schedule for 2021-01-13 from NHL.tv

**Screenshots**
![image](https://user-images.githubusercontent.com/24970374/104507194-06197680-55ac-11eb-83fd-24287b4a3705.png)

**Comment by Sorator** [comment]
Now that I'm trying to actually view a game, it's stuck on a loading swirl; see the top-right:

![image](https://user-images.githubusercontent.com/24970374/104517984-9c559880-55bc-11eb-95da-61dd3132e806.png)

**Comment by NHLGames** [comment]
Are you behind some kind of corporate or university proxy per chance?  To check internet access, the app pings google.com on startup.

**Comment by Sorator** [comment]
Not at all, no.

**Comment by Sorator** [comment]
Several minutes after clicking the button to open the stream, it did finally pop up, at least. So we're back to "it works, just an annoying error".

**Comment by jwallet** [comment]
since you got the error message maybe the connection is slow and it has too retry multiple times to get the stream to play, the internet check only tries once, so i guess that's why it pop-ed, you may want to change  your dns primary to google dns `8.8.8.8` and your secondary to google as well '8.8.4.4` https://developers.google.com/speed/public-dns
