### ISSUE TITLE
Schedule Output

### ISSUE THREAD

**Issue by ulmsky** [NHLGames/NHLGames#283]
I would like to see the ability to schedule the output of a game, essentially creating a recording.

I can foresee an issue with the program deciding which stream to use. Perhaps the user could rank which type of stream they prefer (Home/Away/National/Etc).

**Comment by jwallet** [comment]
we already tried to add a pvr to the app in 1.4, but since the actual recorder does not work properly for everyone, we coded a replay feature instead. so adding a prv was abandonned.
https://github.com/NHLGames/NHLGames/issues/28
https://github.com/NHLGames/NHLGames/issues/106
