### ISSUE TITLE
Kodi/LazyMan App

### ISSUE THREAD

**Issue by deirdeezy** [NHLGames/NHLGames#287]
I apologize is this is crossing the line with this app.  Up until recently, maybe a couple weeks, I was still able to use the LazyMan Kodi app without any issues.  All of a sudden it stopped working.  It behaves normally, you can see it trying to start the stream but then it just drops off.  I am not sure if this is an easy fix or not but I feel the Kodi app is so close to being able to function again.

Again, apologies if this is not something you're interested in.

**Comment by deirdeezy** [comment]
Just to add to the confusion, I just went and tested my Fire Stick and the Kodi/Lazyman app works there...it's just stopped working on my Raspberry Pi...No clue what's happening here.

**Comment by d-kar** [comment]
It's probably hosts file edit problem on rPi. Maybe it got overwritten at some point? Fire stick uses VPN app hosts trick for that

**Comment by deirdeezy** [comment]
Ya I just double checked everything.  The hosts file on my Pi is identical to the VirtualHosts VPN file.  The Pi looks like it's connecting to the game but then just stops trying altogether and doesn't open the stream.

**Comment by deirdeezy** [comment]
I'm using this in both instances.

https://bit.ly/lmhosts
