### ISSUE TITLE
Ad Detection Fails When Casting

### ISSUE THREAD

**Issue by dancurranjr** [NHLGames/NHLGames#291]
Windows 10, When watching a game on VLC Player the Spotify play/pause ad detection works. 
But If I cast the game from VLC to my Chromecast on my TV the ad detections stops working.

**Expected behavior**
Spotify should play during commercials when VLC PLayer is casting the video stream to a Chromecast on a TV

** Workaround **
A workaround, for now, is to open 2 instances of VLC player from the NHL app.
Cast one to the TV with sound
Leave the other one playing LOCAL and mute it.

** Additionally **
It seems like if you connect Spotify to a device that is not your computer (another speaker) the detection fails.

**Comment by dancurranjr** [comment]
A workaround, for now, is to open 2 instances of VLC player from the NHL app.
Cast one to the TV with sound
Leave the other one playing LOCAL and mute it. 
Goofy but it works!

**Comment by murko69** [comment]
Just wanted to say I experience the same issue (also your addition).
Never tried the workaround though. 

Usually I only use MPV (cause I think it's so much better for this app than any other player) but this weekend I was traveling and I forgot my HDMI cable at home and was 'forced' to try VLC using Chromecast instead. 
Worked fine just watching but as you say, the ad detection doesn't work

**Comment by jwallet** [comment]
NHLGames try to detect if your media player is playing sound to play or pause spotify, but because the sound got routed (cast) to an external device it can't do it. So you are right, commercial sounds cannot be detected if you cast the game somewhere else.

**Comment by dancurranjr** [comment]
Thanks JWallet. The workaround I posted has been my go-to solution. Easy enough! 
Love the Spotify feature.
