### ISSUE TITLE
Can't add player args, IndexOutOfRangeException

### ISSUE THREAD

**Issue by Xyxy-** [NHLGames/NHLGames#307]
Hi,

First of all, I'd like to thank you for this software: it's amazingly simple and works really great. One little detail brings me here, though.

## Bug description

I am no longer able to add player args (for mpv, if that matters). When I try to do so, a failure happens. Specifically, I am able to add spaces, but no other characters.

Versions 1.5 and 1.5.1 are affected. Versions 1.4.1 and 1.4.2 are not.

I tried to edit the Config file directly with a text editor, but I didn't meet much success. I can elaborate if that's interesting.

## Steps to reproduce the bug

1. Download `NHLGames-v1.5.1-complete.zip`, unzip it, launch it.
2. Go to the settings panel.
3. In the `Player args` section, try to add an argument after the default one (`--cache=yes`), first with a space (no problem, see `[01:50:48]` in the log below) then a dash (or any other non-space character). At that point, a failure happens.

## Expected behavior

The expected behavior would be to not encounter a failure and being able to pass an argument to a player.

## Console log

> NHLGames Bug Report v 1.5.1.0
> 
> Operating system: Microsoft Windows 8.1 avec Bing 32 Bits - .Net build 4.0.30319.42000	
> Internet: Connection test succeeded, ping google.com succeeded	
> Streamer args enabled:--hls-segment-threads=2 --hls-segment-attempts=9 --hls-segment-timeout=10 --hls-timeout=180	
> Player args enabled:--cache=yes -	
> Selected player: MPV	
> Streamer path: D:\NHLGames-v1.5.1-complete\streamlink\streamlink.exe [on form] [exe found]	
> VLC path: D:\Program Files\VideoLAN\VLC\vlc.exe [on form] [exe found]	
> MPC path: C:\Program Files\Combined Community Codec Pack\MPC\mpc-hc.exe [on form] [exe found]	
> MPV path: D:\NHLGames-v1.5.1-complete\mpv\32bit\mpv.exe [on form] [exe found]
> 
> Console log: 	
> [01:50:26] Status: Setting updated for 'HOSTNAME' to 'freegamez.ga'	
> [01:50:31] Fetching: Game schedule for 2021-06-25 from NHL.tv	
> [01:50:48] Status: Setting updated for 'Players Args' to '--cache=yes '	
> [01:50:49] Error: Code failed at: Running UI thread - With exception: System.IndexOutOfRangeException: L'index se trouve en dehors des limites du tableau.
>    à NHLGames.NHLGamesMetro.txtPlayerArgs_TextChanged(Object sender, EventArgs e)
>    à System.Windows.Forms.Control.OnTextChanged(EventArgs e)
>    à System.Windows.Forms.TextBoxBase.OnTextChanged(EventArgs e)
>    à System.Windows.Forms.TextBoxBase.WmReflectCommand(Message& m)
>    à System.Windows.Forms.TextBoxBase.WndProc(Message& m)
>    à System.Windows.Forms.TextBox.WndProc(Message& m)
>    à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by jwallet** [comment]
yes it has been fixed, thanks for reporting
available in the next release

**Comment by vivian-salino** [comment]
Thank you very much for this fix!

**Comment by Xyxy-** [comment]
Thank you very much for this fix!
