### ISSUE TITLE
Ability to save Player Args for VLC streaming to TV

### ISSUE THREAD

**Issue by gbrown2036** [NHLGames/NHLGames#314]
Excellent app!  Keep up the good work!

With the 1.6.0 version after I choose VLC and  paste the below into Player Args it doesn't save this value when the app is relaunched.  Can it be changed to save this value?

--sout=#http{mux=ts,dst=:8080/stream}

Would it also be possible to have a UI-friendly toggle for "Stream via VLC to TV/device" button so we don't have to remember these player args?  I guess you'd have to have a text box for the port value too.

**Comment by TantumLabs** [comment]
Same here I had to end up rolling back to 1.5.1 to be able to stream it to my TV tonight.

I know they are working on changing this but if you don't overwrite the NHLGames.exe.Config file it won't remove your args.

**Comment by jwallet** [comment]
I fixed it but not release the patch yet, can you stream using the renderer in VLC in the meanwhile ?
https://github.com/NHLGames/NHLGames/wiki/cast-the-game

**Comment by jwallet** [comment]
actually I'm gonna release it
