### ISSUE TITLE
instead of looking for apps in c: drive look in regedit

### ISSUE THREAD

**Issue by jwallet** [NHLGames/NHLGames#47]
cause sometimes people installs their apps in another drive
also, add a link next to VLC path to download it

**Comment by NHLGames** [comment]
This actually produces an error on my machine.  I will investigate

**Comment by jwallet** [comment]
do you have any under HKEY_CURRENT_USER, cause i had nothing there and i only found my x64 vlc, i do have x86 but i did not find it in the registry

**Comment by jwallet** [comment]
i think i found it, my pr will be ready soon

**Comment by jwallet** [comment]
minute i will add also a case for 32 bits
