### ISSUE TITLE
Load games is being run twice - which is creating a deadlock on games.txt

### ISSUE THREAD

**Issue by NHLGames** [NHLGames/NHLGames#54]
I'm not sure if I merged incorrectly but somehow the code to download the schedule is running twice which is causing an error opening games.txt.

Any thoughts @jwallet?

**Comment by jwallet** [comment]
yes, after merge, the url got replaced

**Comment by jwallet** [comment]
looks like some files were not pushed....

**Comment by jwallet** [comment]
pr/41 is the issue,

**Comment by NHLGames** [comment]
Thanks, works properly now.
