### ISSUE TITLE
Progress bar bug on launch

### ISSUE THREAD

**Issue by NHLGames** [NHLGames/NHLGames#62]
When running in the debugger, in the LoadGames function there is the following error:

`Cross-thread operation not valid: Control 'progress' accessed from a thread other than the thread it was created on.`

Processing continues normally however when running the .exe directly outside of Visual Studio, on first launch this causes "No games found".  Clicking Refresh loads the games properly however.

**Comment by jwallet** [comment]
fixed, thanks for the report

**Comment by NHLGames** [comment]
Is there a PR in the works @jwallet? :)

**Comment by jwallet** [comment]
yes

**Comment by NHLGames** [comment]
Do you mean when the user clicks "Refresh"?

It all depends when the user opens the app - the streams are typically available 15 minutes before game time so if they opened the app at 6:44 and there's a delay in checking available games again, I don't know if that would be a good option.

**Comment by jwallet** [comment]
after trying it, i realised it was a bad idea.

**Comment by jwallet** [comment]
this can be close now
