### ISSUE TITLE
new version for spotify api net 2.13

### ISSUE THREAD

**Issue by jwallet** [NHLGames/NHLGames#64]
https://github.com/JohnnyCrazy/SpotifyAPI-NET/releases/tag/2.13.1

**Comment by jwallet** [comment]
can you tell me @NHLGames  if in `\NHLGames\packages\` you have `\SpotifyAPI-NET.2.13.1\` there?
and in `\NHLGames\bin\Debug\AdModules\Spotify\SpotifyAPI.dll` you got the filed that has been modified on 09/03/2017, it should be the last api version.

**Comment by NHLGames** [comment]
@jwallet Yes the packages are there.
