### ISSUE TITLE
do you own the server that host games.txt file

### ISSUE THREAD

**Issue by jwallet** [NHLGames/NHLGames#68]
if you can add the date and time games.txt got edited in the header of the file (like the first line of the line) or a .json file, so we could read that line before starting to read the rest (end of file). after that i can make a class that will hold the games id, so we don't have to read the file every time

**Comment by NHLGames** [comment]
I'm still not sure if there's a benefit to this - if the user opens the app too early, they will have to click refresh anyway to get the ID of the game when it's available (usually 15 minutes before game time).

Do you mean if they just want to refresh the score?  In that case, maybe we should have 2 options - one to refresh score and one to refresh available games.

**Comment by NHLGames** [comment]
Ah so you mean read the entire file only if there have been changes since the last Refresh... hmm that makes sense, I'll see what I can do.

The file gets used by LazyMan also so I would have to see if /u/StevensNJD4 would be able to accomodate the change.

**Comment by d-kar** [comment]
You can just make a new file (like games.json). This way older versions will also still work

**Comment by NHLGames** [comment]
Ok, is it possible to only read 1 line from a remote file using vb.net without downloading the whole thing?

Also, I just realized games.txt never has to be redownloaded for past days once it has been loaded once today - since it will already have all previous games included in it

**Comment by jwallet** [comment]
not using games.txt anymore
