### ISSUE TITLE
Idea: Allow changing domain in settings

### ISSUE THREAD

**Issue by NHLGames** [NHLGames/NHLGames#76]
I was thinking about allowing the user to change the default domain in Settings (from http://nhl.freegamez.gq/) in case we need to change the domain in the back end last minute, we can post the new one on reddit instead of having to upload a new release

**Comment by jwallet** [comment]
Sure it will be useful

**Comment by jwallet** [comment]
So no hard coded domain in the app.. Would you add a txt file of all domains on the same server as version.txt?

**Comment by NHLGames** [comment]
I think it would be a setting in App.config, and it comes set by default to nhl.freegamez.gq.  I'll see if I can work on it tonight
