### ISSUE TITLE
we should go back to previous version for MPV (might be related to streamlink)

### ISSUE THREAD

**Issue by jwallet** [NHLGames/NHLGames#98]
- mpv does not show exception errors if the stream does not start
- apparently there is no fast forward button anymore.
@NHLGames

**Comment by jwallet** [comment]
i might just report this issue to streamlink

**Comment by jwallet** [comment]
found the issue, the media was set to OFF on nhl api. so i can fix that issue, no stream was actually available

**Comment by NHLGames** [comment]
Yes I noticed the controls are a bit different,  I'll probably revert back in the next version
