### ISSUE TITLE
When stream is set to 'Output' to a file problem after first stream

### ISSUE THREAD

**Issue by d-kar** [NHLGames/NHLGames#99]
There is a problem with the progress of loading stream not properly updating when we output to a file.
In Player.vb is assumes 4 steps of progress, but when we output to a file there is no player opening and progress never finishes.
Also would be nice to keep track of which stream is currently writing to disk and be able to stop (i.e. show some red dot on the stream icon if it's recording and pressing it again will finish associated streamlink.exe process)

**Comment by jwallet** [comment]
thanks for this report, never had a chance to test it myself, i thought this feature was broken, apprently it is working on win 10, i was about to disable it like a month ago.

**Comment by d-kar** [comment]
I use this feature all the time to be able to start watching game from the start letter while it's still in progress and to fast forward or pause the game.
Scheduling to PVR games is another feature I really want to see (wanted to implement it myself but couldn't find time for this)

**Comment by NHLGames** [comment]
@jwallet - the workaround for Win7 is to use VLC output param as described here https://github.com/NHLGames/NHLGames/issues/8

**Comment by jwallet** [comment]
i made some changes, so it will open a streamlink window for every game, if output is enabled
